// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqfwpyzkqgvwcxlxdoji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZndweXprcWd2d2N4bHhkb2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MzYwMjQsImV4cCI6MjA4NjUxMjAyNH0.e7CM2-mlpextTOM-LDBBUdS5WFNrTI7bGLz1Paex3ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});